const WA_NUMBER = '5493517606189';

const EVENTS = [
  {
    id: 1,
    title: 'Richie Hawtin',
    subtitle: 'DAHAUS presenta',
    genre: 'electronica',
    genreLabel: 'Electrónica',
    venue: 'Forja Centro de Eventos',
    city: 'Córdoba',
    date: '2025-08-23',
    dateDisplay: 'Sáb 23 Ago 2025',
    time: '23:00',
    price: null,
    badge: 'avail',
    badgeLabel: 'Disponible',
    icon: '🎛️',
  },
  {
    id: 2,
    title: 'Marco Carola',
    subtitle: 'Play It Loud',
    genre: 'electronica',
    genreLabel: 'Electrónica',
    venue: 'La Fábrica',
    city: 'La Calera',
    date: '2025-09-06',
    dateDisplay: 'Sáb 6 Sep 2025',
    time: '23:00',
    price: null,
    badge: 'few',
    badgeLabel: 'Últimos lugares',
    icon: '🎧',
  },
  {
    id: 3,
    title: 'Maceo Plex',
    subtitle: '',
    genre: 'electronica',
    genreLabel: 'Electrónica',
    venue: 'Forja Centro de Eventos',
    city: 'Córdoba',
    date: '2025-09-13',
    dateDisplay: 'Sáb 13 Sep 2025',
    time: '22:00',
    price: null,
    badge: 'avail',
    badgeLabel: 'Disponible',
    icon: '🎛️',
  },
  {
    id: 4,
    title: 'Claptone',
    subtitle: '',
    genre: 'electronica',
    genreLabel: 'Electrónica',
    venue: 'La Estación',
    city: 'Malagueño',
    date: '2025-09-20',
    dateDisplay: 'Sáb 20 Sep 2025',
    time: '22:00',
    price: null,
    badge: 'pre',
    badgeLabel: 'Preventa',
    icon: '🎹',
  },
  {
    id: 5,
    title: 'Monolink',
    subtitle: '',
    genre: 'electronica',
    genreLabel: 'Electrónica',
    venue: 'La Estación',
    city: 'Malagueño',
    date: '2025-10-04',
    dateDisplay: 'Sáb 4 Oct 2025',
    time: '22:00',
    price: null,
    badge: 'avail',
    badgeLabel: 'Disponible',
    icon: '🌊',
  },
  {
    id: 6,
    title: 'John Digweed',
    subtitle: '',
    genre: 'electronica',
    genreLabel: 'Electrónica',
    venue: 'Berta',
    city: 'Alta Gracia',
    date: '2025-10-11',
    dateDisplay: 'Sáb 11 Oct 2025',
    time: '21:00',
    price: null,
    badge: 'avail',
    badgeLabel: 'Disponible',
    icon: '🎶',
  },
  {
    id: 7,
    title: 'Víctor Ruiz & Bart Skils',
    subtitle: 'B2B Set',
    genre: 'electronica',
    genreLabel: 'Electrónica',
    venue: 'La Fábrica',
    city: 'La Calera',
    date: '2025-10-18',
    dateDisplay: 'Sáb 18 Oct 2025',
    time: '23:00',
    price: null,
    badge: 'pre',
    badgeLabel: 'Preventa',
    icon: '🔊',
  },
  {
    id: 8,
    title: 'Cosquín Rock 2026',
    subtitle: 'Festival Nacional',
    genre: 'festival',
    genreLabel: 'Festival',
    venue: 'Plaza Próspero Molina',
    city: 'Cosquín',
    date: '2026-02-07',
    dateDisplay: 'Sáb 7 Feb 2026',
    time: '14:00',
    price: null,
    badge: 'pre',
    badgeLabel: 'Preventa',
    icon: '🎸',
  },
  {
    id: 9,
    title: 'La Renga',
    subtitle: '',
    genre: 'rock',
    genreLabel: 'Rock',
    venue: 'Estadio Atenas',
    city: 'Córdoba',
    date: '2025-11-01',
    dateDisplay: 'Sáb 1 Nov 2025',
    time: '21:00',
    price: null,
    badge: 'avail',
    badgeLabel: 'Disponible',
    icon: '🤘',
  },
  {
    id: 10,
    title: 'MRAK',
    subtitle: '',
    genre: 'electronica',
    genreLabel: 'Electrónica',
    venue: 'La Estación Indoor',
    city: 'Malagueño',
    date: '2025-11-08',
    dateDisplay: 'Sáb 8 Nov 2025',
    time: '23:00',
    price: null,
    badge: 'avail',
    badgeLabel: 'Disponible',
    icon: '🎛️',
  },
  {
    id: 11,
    title: 'Layton Giordani',
    subtitle: '',
    genre: 'electronica',
    genreLabel: 'Electrónica',
    venue: 'La Fábrica',
    city: 'La Calera',
    date: '2025-11-15',
    dateDisplay: 'Sáb 15 Nov 2025',
    time: '23:00',
    price: null,
    badge: 'sold',
    badgeLabel: 'Agotado',
    icon: '🎧',
  },
  {
    id: 12,
    title: 'Festival de la Música',
    subtitle: 'Rock & Pop Nacional',
    genre: 'festival',
    genreLabel: 'Festival',
    venue: 'Estadio Kempes',
    city: 'Córdoba',
    date: '2025-12-06',
    dateDisplay: 'Sáb 6 Dic 2025',
    time: '16:00',
    price: null,
    badge: 'pre',
    badgeLabel: 'Preventa',
    icon: '🎵',
  },
];

function buildWhatsAppLink(event) {
  const text = encodeURIComponent(
    `Hola! Quiero reservar mi lugar para el traslado a ${event.title} — ${event.dateDisplay} — ${event.venue}, ${event.city}. ¿Tienen lugares disponibles?`
  );
  return `https://wa.me/${WA_NUMBER}?text=${text}`;
}